version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - APP_ENV=${APP_ENV:-development}
      - DEBUG=${DEBUG:-true}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped 